Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação usando VisualG]
// Professor   : Jailson
// Descrição   :  O Algoritmo solicita 1 numero, e exibe o antecessor
// Autor(a)    : Walter Santa
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
  num1: inteiro
  resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva (" escreva o primeiro numero: ")
leia(num1)
resultado<- num1-1
escreval ("o antecessor do numero digitado é: ", resultado)


Fimalgoritmo