Algoritmo "AreaCírculo"
// Disciplina   : [Lógica de Programação usando VisualG]
// Professor   : Jailson
// Descrição   : Le o valor do raio de um círculo e calcula sua área.
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
  num1: real
  resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva (" escreva o raio do Círculo: ")
leia(num1)
resultado<- (num1*num1)*pi
escreval ("a area do Círculo é: ", resultado)


Fimalgoritmo