Algoritmo "comprimentoCírculo"
// Disciplina   : [Lógica de Programação usando VisualG]
// Professor   : Jailson
// Descrição   : Le o raio de um círculo e calcula o comprimento da circunferência.
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
  num1: real
  resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva (" escreva o raio do Círculo: ")
leia(num1)
resultado<- 2*num1*pi
escreval ("o comprimento da circunferência é: ", resultado)


Fimalgoritmo