Algoritmo "ConsumoMedio"
// Disciplina   : [Lógica de Programação usando VisualG]
// Professor   : Jailson
// Descrição   : Le a distância percorrida por um carro e o total de combustível gasto. Calcula o consumo médio.
// Autor(a)    : Walter Santa
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
  num1: Real
  num2: Real
  resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("digite a distância percorrida pelo carro: ")
leia(num1)
escreva ("digite o total de combustível gasto: ")
leia(num2)
resultado<- num1/num2
escreval ("o valor do consumo médio é: ", resultado, "Km/L")


Fimalgoritmo