Algoritmo "ControleCommits"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição    : Verifica se houve commits na semana.
// Autor(a)    : Walter
// Data atual  : 13/04/2026
Var
// Seção de Declarações das variáveis 
   num1: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Numero de commits: ")
   leia(num1)

   se num1 > 0 entao
      escreval("Repositorio atualizado")
   fimse
   Fimalgoritmo