Algoritmo "Cronometo"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   :  cronometro que conta o tempo
// Data atual  : 01/04/2026
Var
// Seção de Declarações das variáveis 
contadora1, contadora2 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Para contadora1 de 0 até 59 passo 1 faça
Para contadora2 de 0 até 59 passo 1 faça
escreval(contadora1, " : ", contadora2)

  fimpara
fimpara


Fimalgoritmo