Algoritmo "ExercicioPara"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   : Um program que efetua um Calculo e no final apresente o um trigo para a primeira casa de um tabuleiro de xadrez 2 trigos para o segundo 4 para o terceiro e assim suscetivamente e somasse o quanto eu ganhei em cada quadro
// Data atual  : 01/04/2026
Var
// Seção de Declarações das variáveis 
contadora: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Para contadora de 0 até 100 passo 10 faça
escreval(contadora)
fimpara


Fimalgoritmo