Algoritmo "Exercicio02Para"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   : Apresentar os quadrados dos numeros inteiros de 15 a 200.
// Data atual  : 01/04/2026
Var
// Seção de Declarações das variáveis 
num1, contadora, resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Tabuada")
escreval ("Digite um numero: ")
leia(num1)
Para contadora de 1 até 10 passo 1 faça
resultado <- contadora * num1
escreval(num1, " x ",contadora, " = ", resultado)
fimpara


Fimalgoritmo