Algoritmo "L01G"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição    : Soma e multiplica combinações entre quatro números.
// Autor(a)    : Walter
// Data atual  : 14/04/2026
Var
// Seção de Declarações das variáveis 
   num1, num2, num3, num4: inteiro
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite numero 1: ")
   leia(num1)
   escreva("Digite numero 2: ")
   leia(num2)
   escreva("Digite numero 3: ")
   leia(num3)
   escreva("Digite numero 4: ")
   leia(num4)

   escreval("Soma 1+2: ", num1 + num2)
   escreval("Produto 1*2: ", num1 * num2)

   escreval("Soma 1+3: ", num1 + num3)
   escreval("Produto 1*3: ", num1 * num3)

   escreval("Soma 1+4: ", num1 + num4)
   escreval("Produto 1*4: ", num1 * num4)

   escreval("Soma 2+3: ", num2 + num3)
   escreval("Produto 2*3: ", num2 * num3)

   escreval("Soma 2+4: ", num2 + num4)
   escreval("Produto 2*4: ", num2 * num4)

   escreval("Soma 3+4: ", num3 + num4)
   escreval("Produto 3*4: ", num3 * num4)
   Fimalgoritmo