Algoritmo "Media das notas"
// Disciplina   : [Lógica de Programação usando VisualG]
// Professor   : Jailson
// Descrição   :  O Algoritmo solicita 3 notas, e exibe a media
// Autor(a)    : Walter Santa
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
  nota1: Real
  nota2: Real
  nota3: Real
  resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("digite a primeira nota: ")
leia(nota1)
escreva ("digite a segunda nota: ")
leia(nota2)
escreva ("digite a terceira nota: ")
leia(nota3)
resultado<- (nota1+nota2+nota3)\3
escreval ("a media das notas é: ", resultado)


Fimalgoritmo