Algoritmo " perimetroRetangulo2"
// Disciplina   : [Lógica de Programação usando VisualG]
// Professor   : Jailson
// Descrição   : Le a largura e a altura de um retângulo e calcula seu perímetro.
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
  num1: inteiro
  num2: inteiro
  resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva (" escreva o largura do retângulo: ")
leia(num1)
escreva (" escreva a altura do retângulo: ")
leia(num2)
resultado<- (num2+num1)*2
escreval ("o perímetro do retângulo é: ", resultado)


Fimalgoritmo