Algoritmo "tabuada"
// Disciplina   : [Lógica de Programação com VIsualG]
// Professor   : Jailson
// Descrição   : Apresentar os resultados de uma tabuada de multiplicar (de 1 a até 10) de um numero qualquer
// Autor(a)    : Walter Santana Riva
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
contador: inteiro
num1: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
contador <- 1
escreva ("Digite um numero inteiro: ")
leia(num1)
enquanto contador <11 faça
escreval (num1,"x",contador,"=",num1*contador)
contador <- contador+1
fimenquanto




Fimalgoritmo
