Algoritmo "TomadaDecisaoSimples"
// Disciplina   : [Lógica de Programação com VisualG e JavaScript]
// Professor   : Jailson
// Descrição   :  O Algoritmo solicita 1 numero em metros e exibe em centimetros
// Autor(a)    : Walter Santa
// Data atual  : 23/03/2026
Var
// Seção de Declarações das variáveis 
  numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Programa de TOmada de Decissão Simples")
escreval ("Digite um valor")
leia(numero)
se numero > 10 então
escreval ("Numero digitado é maior que 10")
senão
se numero = 10 então
escreval ("Numero digitado é 10")
senão
escreval ("Numero digitado é menor que 10")
fimse
fimse


Fimalgoritmo