Algoritmo "Valor da Compra"
// Disciplina   : [Lógica de Programação usando VisualG]
// Professor   : Jailson
// Descrição   : Programa que solicita a quantidade de produtos adiquiridos e
// comprados, solicita o preço e ao final exibe o valo total da compra
// Autor(a)    : Walter Santa
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
  preco: Real
  quantidade : inteiro
  total: real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("digite o o preço do produto: ")
leia(preco)
escreva ("digite a quantidade: ")
leia(quantidade )
  total <- preco*quantidade)
escreval ("o preço total dos produtos adquiridos é:", total)


Fimalgoritmo